#!/usr/bin/env python3
"""
build_rollups.py — Regenerate data/derived/* from the event ledger + Challenger layer.

Aggregation is irreversible, so we roll up in this VIEW-prep layer, never in storage.
Deterministic and pure: no wall-clock in the output, everything sorted, so re-running on the
same inputs yields byte-identical files. B-tiers are reported separately and NEVER collapsed.

Outputs (seed.md §5.1 derived/):
  • ai-attribution-timeseries.json — per-month event counts + headcount sums by B-tier.
  • discrepancy-series.json        — Challenger AI-CITED total vs. our B1 firm-stated,
                                      A1/A2-verified total. The GAP is the measurement.
  • sector-rollup.json             — per-sector counts/headcount, broken out by B-tier.

Usage:  python scripts/build_rollups.py [--data-dir data]
"""
import argparse
import json
import os

B_TIERS = ["B1", "B2", "B3", "B0"]


def _load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _month(ev):
    return (ev.get("date_announced") or "")[:7]


def _hc(ev):
    return ev.get("headcount") or 0


def _empty_bucket():
    return {t: 0 for t in B_TIERS}


def build_attribution_timeseries(events):
    months = {}
    for ev in events:
        m = _month(ev)
        if not m:
            continue
        b = ev.get("ai_attribution")
        if b not in B_TIERS:
            continue
        bucket = months.setdefault(m, {"counts": _empty_bucket(), "headcount": _empty_bucket()})
        bucket["counts"][b] += 1
        bucket["headcount"][b] += _hc(ev)
    return {
        "meta": {
            "description": "Per-month event counts and headcount sums by AI-attribution tier. "
                           "B1/B2/B3/B0 are reported separately and never summed into one headline.",
            "generated_from": "ai-layoff-events.json",
            "note": "AUTO-GENERATED by build_rollups.py — never hand-edit.",
        },
        "months": [
            {"month": m, "counts": months[m]["counts"], "headcount": months[m]["headcount"]}
            for m in sorted(months)
        ],
    }


def build_discrepancy(events, challenger_months):
    # Our stricter total: B1 (stated-by-firm) AND A1/A2-verified (seed.md §4).
    lm = {}  # month -> {"hc": int, "count": int}
    for ev in events:
        if ev.get("ai_attribution") == "B1" and ev.get("event_confidence") in ("A1", "A2"):
            m = _month(ev)
            if not m:
                continue
            slot = lm.setdefault(m, {"hc": 0, "count": 0})
            slot["hc"] += _hc(ev)
            slot["count"] += 1

    chal = {c["month"]: c.get("ai_cited_cuts") for c in challenger_months}
    all_months = sorted(set(chal) | set(lm))
    rows = []
    for m in all_months:
        ai_cited = chal.get(m)  # may be None if month absent from Challenger
        b1 = lm.get(m, {"hc": 0, "count": 0})
        gap = (ai_cited - b1["hc"]) if ai_cited is not None else None
        rows.append({
            "month": m,
            "challenger_ai_cited": ai_cited,
            "lm_b1_verified": b1["hc"],
            "lm_b1_event_count": b1["count"],
            "gap": gap,
        })
    return {
        "meta": {
            "description": "The strategic-layer measurement: Challenger AI-CITED total (their claim) "
                           "vs. LaborMarket.ai B1 firm-stated, A1/A2-verified total (our stricter standard). "
                           "The GAP is the metric — the distance between claimed and corroborated — NOT an error to reconcile.",
            "generated_from": "ai-layoff-events.json + challenger-monthly.json",
            "note": "AUTO-GENERATED by build_rollups.py — never hand-edit.",
        },
        "months": rows,
    }


def build_sector(events):
    sectors = {}
    for ev in events:
        s = ev.get("sector") or "Unspecified"
        slot = sectors.setdefault(s, {"event_count": 0, "total_headcount": 0, "by_b_tier": _empty_bucket()})
        slot["event_count"] += 1
        slot["total_headcount"] += _hc(ev)
        b = ev.get("ai_attribution")
        if b in B_TIERS:
            slot["by_b_tier"][b] += 1
    return {
        "meta": {
            "description": "Per-sector event counts and headcount, broken out by B-tier (never collapsed).",
            "generated_from": "ai-layoff-events.json",
            "note": "AUTO-GENERATED by build_rollups.py — never hand-edit.",
        },
        "sectors": [
            {"sector": s, **sectors[s]}
            for s in sorted(sectors, key=lambda x: (-sectors[x]["total_headcount"], x))
        ],
    }


def build_rollups(data_dir="data"):
    events = _load(os.path.join(data_dir, "ai-layoff-events.json")).get("events", [])
    challenger_path = os.path.join(data_dir, "challenger-monthly.json")
    challenger = _load(challenger_path).get("months", []) if os.path.exists(challenger_path) else []
    return {
        "ai-attribution-timeseries.json": build_attribution_timeseries(events),
        "discrepancy-series.json": build_discrepancy(events, challenger),
        "sector-rollup.json": build_sector(events),
    }


def write_rollups(data_dir="data"):
    out_dir = os.path.join(data_dir, "derived")
    os.makedirs(out_dir, exist_ok=True)
    rollups = build_rollups(data_dir)
    for name, obj in rollups.items():
        with open(os.path.join(out_dir, name), "w", encoding="utf-8") as f:
            json.dump(obj, f, indent=2, ensure_ascii=False)
            f.write("\n")
    return list(rollups)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", default="data")
    args = ap.parse_args()
    written = write_rollups(args.data_dir)
    print(f"  ✓ rollups regenerated: {', '.join(written)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
